apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: bridges.bridge.io
spec:
  group: bridge.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                bridge_name:
                  type: string
                value:
                  type: string
                namespace:
                  type: string
  scope: Namespaced
  names:
    plural: bridges
    singular: bridge
    kind: Bridge
    shortNames:
    - brg
